name: Docker Build and Push

on:
  push:
    branches:
      - main # Trigger the workflow on pushes to the `main` branch
  pull_request:
    branches:
      - main # Optional: Trigger on pull requests to `main`

jobs:
  docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Required to push Docker images to GitHub Packages
      id-token: write # Required for authentication with OIDC providers

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

          # Step 4: Build and push Docker image
      - name: Build and Push Docker Image
        run: |
          docker build -f ci_cd/python/Dockerfile -t ghcr.io/kelvinbdavis/talk-booking:cicd-python3.11-slim .
          docker push ghcr.io/kelvinbdavis/talk-booking:cicd-python3.11-slim
