name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  combined:
    name: Code Quality and Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV

      - name: Install Dependencies
        run: |
          cd services/talk-booking/
          poetry install

      - name: Run Code Quality Tools
        run: |
          cd services/talk-booking/
          poetry run flake8 .
          poetry run black . --check
          poetry run isort . --check-only --profile black
          poetry run bandit .
          poetry run safety check

      - name: Run Tests with Coverage
        run: |
          cd services/talk-booking/
          poetry run python -m pytest --junitxml=report.xml --cov=./ --cov-report=xml tests/unit tests/integration

      - name: Upload Coverage Report to Codecov
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -R services/talk-booking/

      - name: Upload Test Reports
        uses: actions/upload-artifact@v3
        with:
          name: junit-report
          path: services/talk-booking/report.xml
